package com.pusilkom.hris.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AuthItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public AuthItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andUserCreateIsNull() {
            addCriterion("user_create is null");
            return (Criteria) this;
        }

        public Criteria andUserCreateIsNotNull() {
            addCriterion("user_create is not null");
            return (Criteria) this;
        }

        public Criteria andUserCreateEqualTo(String value) {
            addCriterion("user_create =", value, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateNotEqualTo(String value) {
            addCriterion("user_create <>", value, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateGreaterThan(String value) {
            addCriterion("user_create >", value, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateGreaterThanOrEqualTo(String value) {
            addCriterion("user_create >=", value, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateLessThan(String value) {
            addCriterion("user_create <", value, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateLessThanOrEqualTo(String value) {
            addCriterion("user_create <=", value, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateLike(String value) {
            addCriterion("user_create like", value, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateNotLike(String value) {
            addCriterion("user_create not like", value, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateIn(List<String> values) {
            addCriterion("user_create in", values, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateNotIn(List<String> values) {
            addCriterion("user_create not in", values, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateBetween(String value1, String value2) {
            addCriterion("user_create between", value1, value2, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserCreateNotBetween(String value1, String value2) {
            addCriterion("user_create not between", value1, value2, "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateIsNull() {
            addCriterion("user_update is null");
            return (Criteria) this;
        }

        public Criteria andUserUpdateIsNotNull() {
            addCriterion("user_update is not null");
            return (Criteria) this;
        }

        public Criteria andUserUpdateEqualTo(String value) {
            addCriterion("user_update =", value, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateNotEqualTo(String value) {
            addCriterion("user_update <>", value, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateGreaterThan(String value) {
            addCriterion("user_update >", value, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateGreaterThanOrEqualTo(String value) {
            addCriterion("user_update >=", value, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateLessThan(String value) {
            addCriterion("user_update <", value, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateLessThanOrEqualTo(String value) {
            addCriterion("user_update <=", value, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateLike(String value) {
            addCriterion("user_update like", value, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateNotLike(String value) {
            addCriterion("user_update not like", value, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateIn(List<String> values) {
            addCriterion("user_update in", values, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateNotIn(List<String> values) {
            addCriterion("user_update not in", values, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateBetween(String value1, String value2) {
            addCriterion("user_update between", value1, value2, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateNotBetween(String value1, String value2) {
            addCriterion("user_update not between", value1, value2, "userUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateIsNull() {
            addCriterion("timestamp_create is null");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateIsNotNull() {
            addCriterion("timestamp_create is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateEqualTo(Date value) {
            addCriterion("timestamp_create =", value, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateNotEqualTo(Date value) {
            addCriterion("timestamp_create <>", value, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateGreaterThan(Date value) {
            addCriterion("timestamp_create >", value, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp_create >=", value, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateLessThan(Date value) {
            addCriterion("timestamp_create <", value, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateLessThanOrEqualTo(Date value) {
            addCriterion("timestamp_create <=", value, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateIn(List<Date> values) {
            addCriterion("timestamp_create in", values, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateNotIn(List<Date> values) {
            addCriterion("timestamp_create not in", values, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateBetween(Date value1, Date value2) {
            addCriterion("timestamp_create between", value1, value2, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampCreateNotBetween(Date value1, Date value2) {
            addCriterion("timestamp_create not between", value1, value2, "timestampCreate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateIsNull() {
            addCriterion("timestamp_update is null");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateIsNotNull() {
            addCriterion("timestamp_update is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateEqualTo(Date value) {
            addCriterion("timestamp_update =", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateNotEqualTo(Date value) {
            addCriterion("timestamp_update <>", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateGreaterThan(Date value) {
            addCriterion("timestamp_update >", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp_update >=", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateLessThan(Date value) {
            addCriterion("timestamp_update <", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateLessThanOrEqualTo(Date value) {
            addCriterion("timestamp_update <=", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateIn(List<Date> values) {
            addCriterion("timestamp_update in", values, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateNotIn(List<Date> values) {
            addCriterion("timestamp_update not in", values, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateBetween(Date value1, Date value2) {
            addCriterion("timestamp_update between", value1, value2, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateNotBetween(Date value1, Date value2) {
            addCriterion("timestamp_update not between", value1, value2, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(name) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("upper(description) like", value.toUpperCase(), "description");
            return (Criteria) this;
        }

        public Criteria andUserCreateLikeInsensitive(String value) {
            addCriterion("upper(user_create) like", value.toUpperCase(), "userCreate");
            return (Criteria) this;
        }

        public Criteria andUserUpdateLikeInsensitive(String value) {
            addCriterion("upper(user_update) like", value.toUpperCase(), "userUpdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.auth_item
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}