package com.pusilkom.hris.model;

import java.io.Serializable;
import java.util.Date;

public class AuthItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item.user_create
     *
     * @mbg.generated
     */
    private String userCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item.user_update
     *
     * @mbg.generated
     */
    private String userUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item.timestamp_create
     *
     * @mbg.generated
     */
    private Date timestampCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item.timestamp_update
     *
     * @mbg.generated
     */
    private Date timestampUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item.id
     *
     * @return the value of public.auth_item.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item.id
     *
     * @param id the value for public.auth_item.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item.name
     *
     * @return the value of public.auth_item.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item.name
     *
     * @param name the value for public.auth_item.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item.type
     *
     * @return the value of public.auth_item.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item.type
     *
     * @param type the value for public.auth_item.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item.description
     *
     * @return the value of public.auth_item.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item.description
     *
     * @param description the value for public.auth_item.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item.user_create
     *
     * @return the value of public.auth_item.user_create
     *
     * @mbg.generated
     */
    public String getUserCreate() {
        return userCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item.user_create
     *
     * @param userCreate the value for public.auth_item.user_create
     *
     * @mbg.generated
     */
    public void setUserCreate(String userCreate) {
        this.userCreate = userCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item.user_update
     *
     * @return the value of public.auth_item.user_update
     *
     * @mbg.generated
     */
    public String getUserUpdate() {
        return userUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item.user_update
     *
     * @param userUpdate the value for public.auth_item.user_update
     *
     * @mbg.generated
     */
    public void setUserUpdate(String userUpdate) {
        this.userUpdate = userUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item.timestamp_create
     *
     * @return the value of public.auth_item.timestamp_create
     *
     * @mbg.generated
     */
    public Date getTimestampCreate() {
        return timestampCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item.timestamp_create
     *
     * @param timestampCreate the value for public.auth_item.timestamp_create
     *
     * @mbg.generated
     */
    public void setTimestampCreate(Date timestampCreate) {
        this.timestampCreate = timestampCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item.timestamp_update
     *
     * @return the value of public.auth_item.timestamp_update
     *
     * @mbg.generated
     */
    public Date getTimestampUpdate() {
        return timestampUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item.timestamp_update
     *
     * @param timestampUpdate the value for public.auth_item.timestamp_update
     *
     * @mbg.generated
     */
    public void setTimestampUpdate(Date timestampUpdate) {
        this.timestampUpdate = timestampUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthItem other = (AuthItem) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getUserCreate() == null ? other.getUserCreate() == null : this.getUserCreate().equals(other.getUserCreate()))
            && (this.getUserUpdate() == null ? other.getUserUpdate() == null : this.getUserUpdate().equals(other.getUserUpdate()))
            && (this.getTimestampCreate() == null ? other.getTimestampCreate() == null : this.getTimestampCreate().equals(other.getTimestampCreate()))
            && (this.getTimestampUpdate() == null ? other.getTimestampUpdate() == null : this.getTimestampUpdate().equals(other.getTimestampUpdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getUserCreate() == null) ? 0 : getUserCreate().hashCode());
        result = prime * result + ((getUserUpdate() == null) ? 0 : getUserUpdate().hashCode());
        result = prime * result + ((getTimestampCreate() == null) ? 0 : getTimestampCreate().hashCode());
        result = prime * result + ((getTimestampUpdate() == null) ? 0 : getTimestampUpdate().hashCode());
        return result;
    }
}