package com.pusilkom.hris.model;

import java.io.Serializable;

public class AuthItemChildKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item_child.parent
     *
     * @mbg.generated
     */
    private String parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auth_item_child.child
     *
     * @mbg.generated
     */
    private String child;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.auth_item_child
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item_child.parent
     *
     * @return the value of public.auth_item_child.parent
     *
     * @mbg.generated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item_child.parent
     *
     * @param parent the value for public.auth_item_child.parent
     *
     * @mbg.generated
     */
    public void setParent(String parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auth_item_child.child
     *
     * @return the value of public.auth_item_child.child
     *
     * @mbg.generated
     */
    public String getChild() {
        return child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auth_item_child.child
     *
     * @param child the value for public.auth_item_child.child
     *
     * @mbg.generated
     */
    public void setChild(String child) {
        this.child = child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item_child
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthItemChildKey other = (AuthItemChildKey) that;
        return (this.getParent() == null ? other.getParent() == null : this.getParent().equals(other.getParent()))
            && (this.getChild() == null ? other.getChild() == null : this.getChild().equals(other.getChild()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auth_item_child
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getParent() == null) ? 0 : getParent().hashCode());
        result = prime * result + ((getChild() == null) ? 0 : getChild().hashCode());
        return result;
    }
}